In [0]:
%tensorflow_version 2.x

In [0]:
import tensorflow as tf

In [6]:
print(tf.__version__)

2.2.0-rc2


## 텐서플로우 수학연산
* Numpy에서 사용 되는 대부분의 수학 연산을 동일한 방법으로 사용 가능
* 텐서플로우 연산자 들은 TPU, GPU 와 같은 가속 하드웨어를 이용해 수행 가능

In [0]:
#(2, 3)
tensor_a = tf.constant([[1., 2., 3.],
                        [4., 5., 6.]])
#(2, 3)
tensor_b = tf.constant([[7., 8., 9.],
                        [10., 11., 12.]])

In [8]:
tensor_c = tensor_a + tensor_b
tensor_c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 8., 10., 12.],
       [14., 16., 18.]], dtype=float32)>

In [10]:
tensor_d = tf.math.square(tensor_c)
tensor_d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 64., 100., 144.],
       [196., 256., 324.]], dtype=float32)>

In [11]:
tensor_d = tf.square(tensor_c)
tensor_d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 64., 100., 144.],
       [196., 256., 324.]], dtype=float32)>

In [12]:
tensor_e = tf.math.log(tensor_d)
tensor_e

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4.158883 , 4.6051702, 4.9698133],
       [5.278115 , 5.5451775, 5.7807436]], dtype=float32)>

## 텐서플로우 연산의 미분
* 미분 가능한 연산들에 대해서 자동으로 미분계산
* GradientTape 컨텍스 내에서 .watch() 메서드를 통해 해당 텐서로 수행하는 연산에 대한 미분 확인(상수 텐서의 경우)

In [13]:
tensor_a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [15]:
with tf.GradientTape() as tape:
  tape.watch(tensor_a)
  tensor_c = tf.square(tensor_a + tensor_b)
  gradient_ca = tape.gradient(target=tensor_c, sources=tensor_a)
  print(gradient_ca)

tf.Tensor(
[[16. 20. 24.]
 [28. 32. 36.]], shape=(2, 3), dtype=float32)


  * 변수 텐서의 경우 .watch() 메서드를 사용하지 않아도 연산에 대한 미분 확인 가능

In [0]:
tensor_var_a = tf.Variable([[1., 2., 3.],
                            [4., 5., 6.]])

tensor_var_b = tf.Variable([[7., 8., 9.],
                            [10., 11., 12.]])

In [18]:
tensor_var_a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [19]:
tensor_var_b

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)>

In [21]:
with tf.GradientTape() as tape:
  tensor_var_c = tf.square(tensor_var_a + tensor_var_b)
  gradient_ca = tape.gradient(target=tensor_var_c, sources=tensor_var_a)
  print(gradient_ca)

tf.Tensor(
[[16. 20. 24.]
 [28. 32. 36.]], shape=(2, 3), dtype=float32)
