In [ ]:
%tensorflow_version 2.x

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.2.0-rc2


## tf.constant(상수)
* 텐서플로우에 사용되는 텐서(데이터) 유형 중 하나
* 상수형 텐서로써 할당된 값의 변경이 불가
* Numpy의 ndarray 와 유사한 속성들을(ndim, shape, dtype) 가짐
* .numpy() 메서드를 통해 텐서에 들어 있는 데이터를 Numpy ndarray 형태로 가져옴

In [ ]:
# (2, 2, 3)
d3_tensor = tf.constant([[[1, 2, 3],
                          [4, 5, 6]],
                         [[-1, -2, -3],
                          [-4, -5, -6]]])

In [ ]:
d3_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[-1, -2, -3],
        [-4, -5, -6]]], dtype=int32)>

In [ ]:
d3_tensor[0, 0, 0] = 0

TypeError: ignored

In [ ]:
np_d3_tensor = d3_tensor.numpy()

In [ ]:
np_d3_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[-1, -2, -3],
        [-4, -5, -6]]], dtype=int32)

In [ ]:
np_d3_tensor[0, 0, 0] = 0

In [ ]:
np_d3_tensor

array([[[ 0,  2,  3],
        [ 4,  5,  6]],

       [[-1, -2, -3],
        [-4, -5, -6]]], dtype=int32)

In [ ]:
print(d3_tensor.ndim)
print(d3_tensor.shape)
print(d3_tensor.dtype)

3
(2, 2, 3)
<dtype: 'int32'>


## tf.Variable(변수)
* 텐서플로우에 사용되는 텐서(데이터) 유형 중 하나
* Numpy의 ndarray 와 유사한 속성들을(ndim(X), shape, dtype) 가짐
* tf.constant(상수) 와는 다르게 assign(value) 같은 메소드를 통해 할당된 값의 변경 가능
* .numpy() 메서드를 통해 텐서에 들어 있는 데이터를 Numpy ndarray 형태로 가져옴
* 인공신경망의 변수(가중치, 바이어스) 구성에 사용됨

In [ ]:
import numpy as np

In [ ]:
d3_np_tensor = np.array([[[1, 2, 3],
                          [4, 5, 6]],
                         [[-1, -2, -3],
                          [-4, -5, -6]]])

In [ ]:
d3_np_tensor = d3_np_tensor.astype(np.float32)

In [ ]:
d3_np_tensor.dtype

dtype('float32')

In [ ]:
d3_var_tensor = tf.Variable(d3_np_tensor)

In [ ]:
d3_var_tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[-1., -2., -3.],
        [-4., -5., -6.]]], dtype=float32)>

In [ ]:
print(d3_var_tensor.ndim)

AttributeError: ignored

In [ ]:
print(d3_var_tensor.shape)
print(d3_var_tensor.dtype)

(2, 2, 3)
<dtype: 'float32'>


In [ ]:
d3_var_tensor[0, 0, 0].assign(0)

<tf.Variable 'UnreadVariable' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[-1., -2., -3.],
        [-4., -5., -6.]]], dtype=float32)>